apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: go-kmhnonwi 
  janus-idp.io/tekton: go-kmhnonwi
  backstage.io/kubernetes-id: go-kmhnonwi
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: go-kmhnonwi
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml